### PR TITLE
Fix Warning: Failed prop type: Invalid prop value supplied to Select

### LINKED ISSUE #286: Warning: Failed prop type: Invalid prop `value` supplied to `Select`
Hello,

I'm experiencing a warning with `Select` when `multiple` prop is true. Can you confirm this issue?

**Bug description**

I get a warning when I use `Select` with the `multiple` prop and pass an array to `value` prop:

```
<Select multiple={true} value={[]} onChange={()=>{}}>
  <option key='1' value='1'>One</option>
  <option key='2' value='2'>Two</option>
</Select>
```

```
Warning: Failed prop type: Invalid prop `value` supplied to `Select`
```

**To Reproduce**
1. Instantiate Select with multiple={true} and value={[]}
2. See warning in developer tools console

**Expected behavior**

No warning.

**Versions**
- `react-bulma-components`: 3.4.0
- `bulma`: 0.8.2
- `react`: 17.0.1
- `Browser`: Google Chrome 87

**Additional context**

I have fixed the issue locally by changing the `value` constraint in `Select.js`:

```
value: PropTypes.oneOfType([PropTypes.string, PropTypes.number, PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number]))]),
```

I am willing to create a pull request in the `next` branch so it can be fixed for 4.0 (I can also do a pull request for 3.4.0).

What do you think?

### PR DESCRIPTION
**Pull request by 1r3n33**
Closes #286. Please review.

### CODE REVIEW

File: src/components/form/components/select.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const Select = ({
       renderAs="select"
       {...props}
       multiple={multiple}
-      value={value}
+      value={value !== undefined ? value : multiple ? [] : ''}
```
Comment (MrCreeper1008) [inline src/components/form/components/select.js:39]: nested ternary is unreadable. consider extracting this as a function named for example `getDefaultValue()` or just `defaultValue()`.

Comment (MrCreeper1008) [inline src/components/form/components/select.js:39]: nested ternary is unreadable. consider extracting this as a function named for example `getDefaultValue()` or just `defaultValue()`.

File: src/components/form/components/__test__/select.test.js [hunk 2]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
     expect(component.toJSON()).toMatchSnapshot();
   });
+  it('Should be multioption and should accept number array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select multiple value={[1,2,3]}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).not.toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:56]: this assertion is not necessary.

File: src/components/form/components/__test__/select.test.js [hunk 3]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should be multioption and should accept string array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select multiple value={['1','2','3']}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).not.toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:66]: this assertion is unnecessary.

File: src/components/form/components/__test__/select.test.js [hunk 4]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should be multioption and should not accept non array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select multiple value={1}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:76]: this assertion is unnecessary.

File: src/components/form/components/__test__/select.test.js [hunk 5]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should accept number value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select value={1}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).not.toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:86]: this assertion is unnecessary.

File: src/components/form/components/__test__/select.test.js [hunk 6]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should accept string value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select value={'1'}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).not.toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:96]: this assertion is unnecessary.

File: src/components/form/components/__test__/select.test.js [hunk 7]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should accept string value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select value={'1'}>
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:92]: stylistic issue: prefer double quote for jsx string instead of single quote inside curly braces:
```
<Select value="1">
```

File: src/components/form/components/__test__/select.test.js [hunk 8]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).not.toBeCalled();
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should not accept array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select value={[1,2,3]}>
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:102]: stylistic issue: add space between comma and next item in the array.

File: src/components/form/components/__test__/select.test.js [hunk 9]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
     );
     expect(component.toJSON()).toMatchSnapshot();
   });
+  it('Should be multioption and should accept number array value', () => {
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:49]: Consider grouping test cases for select values in a `describe` block.

File: src/components/form/components/__test__/select.test.js [hunk 10]
```diff
@@ -46,4 +46,64 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should not accept array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(
+      <Select value={[1,2,3]}>
+      </Select>,
+    );
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).toBeCalled();
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:106]: this assertion is unnecessary.

File: src/components/form/components/select.js [hunk 11]
```diff
@@ -57,13 +57,21 @@ Select.propTypes = {
...
+        propName,
+        componentName);
+    } else {
+      PropTypes.checkPropTypes(
+        { [propName]: PropTypes.oneOfType([PropTypes.string, PropTypes.number]) },
+        props,
+        propName,
+        componentName);
+    }
+  },
```
Comment (MrCreeper1008) [inline src/components/form/components/select.js:74]: is there any reason why you have decided to use a custom prop type checking function instead of:
```
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number,
  PropTypes.arrayOf(
    PropTypes.oneOfType([PropTypes.string, PropTypes.number])
  )
])
```
?

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
Thank you for your PR! A couple changes:
- asserting that it won't throw errors in console is unnecessary
- consider grouping test cases for testing `value` prop in a `describe` block.
- avoid nested ternary expressions if possible
- any reason why you have used a custom prop type function?

thank you for your contribution!

File: src/components/form/components/select.js (hunk 11 above)
Comment (1r3n33) [reply src/components/form/components/select.js:74]: Hello @MrCreeper1008, thank you for reviewing.

Using a function allowed me to remove one flaw in the initial proposition:
The prop type check is actually dependent of the `multiple` value. As you can see, if `multiple` is `true` we really want an array of strings/numbers. But in case, `multiple` is `false`, providing such array is a mistake which the initial check is not capable to catch.
I feel this function enables a more complete fix as it removes initial proposition flaw.

Also, this is the reason why I have added tests that check different combination of `multiple` and `value`. For some test cases, I actually check it throws errors in case of misconfiguration.

Comment (MrCreeper1008) [reply src/components/form/components/select.js]: you are correct, in this case asserting that no console errors will be thrown is fine.

File: src/components/form/components/select.js [hunk 12]
```diff
@@ -21,30 +21,36 @@ const Select = ({
...
-      [`is-${color}`]: color,
-      'is-loading': loading,
-      'is-multiple': multiple,
-    })}
-    style={style}
-  >
+}) => {
+  function defaultValue(isMultiple) {
+    return isMultiple ? [] : '';
+  }
```
Comment (MrCreeper1008) [inline src/components/form/components/select.js:27]: the parameter `isMultiple` is unnecessary since the `multiple` prop is in scope. also please add a jsdoc comment (`/** */`) above the function to describe what it does.

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
Nice job! Just tww more changes:
- i made a comment on the `defaultValue` function.
- please group the test cases for `value` prop into one `describe` block.

File: src/components/form/components/__test__/select.test.js [hunk 13]
```diff
@@ -47,3 +47,20 @@ describe('Select component', () => {
...
+    spy.mockRestore();
+  });
+  it('Should not be multioption and should not accept array value', () => {
+    const spy = jest.spyOn(console, 'error').mockImplementation();
+    const component = renderer.create(<Select value={[1, 2, 3]}></Select>);
+    expect(component.toJSON()).toMatchSnapshot();
+    expect(spy).toBeCalled();
+    spy.mockRestore();
+  });
+});
```
Comment (MrCreeper1008) [inline src/components/form/components/__test__/select.test.js:66]: Can you move this `describe` block inside the `'Select component'` describe block?

File: src/components/form/components/select.js [hunk 14]
```diff
@@ -57,13 +66,29 @@ Select.propTypes = {
...
   loading: PropTypes.bool,
-  value: PropTypes.oneOfType([
-    PropTypes.string,
-    PropTypes.number,
-    PropTypes.arrayOf(
-      PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
-    ),
-  ]),
+  value: function (props, propName, componentName) {
+    if (props['multiple']) {
```
Comment (MrCreeper1008) [inline src/components/form/components/select.js:70]: prefer dot notation (`props.multiple`) over bracket notation.

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
Just some minor stylistic issues:
- move the describe block for testing value prop inside the describe block for testing `Select` component
- prefer dot notation over bracket notation

thank you!

**Review by MrCreeper1008 — APPROVED** [review]
LGTM! Thank you for your contribution.
